eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
user:
  name: xiaowei
  age: 13
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true& serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 4
    host: localhost
    password: 123456
    port: 6379
    jedis:
      pool:
        #jedis线程池最大活跃数
        max-active: 20
        #jedis线程池最大闲置数
        max-idle: 15
        # jedis线程池最小闲置数
        min-idle: 5
        # jedis线程池最大等待时间，ms为单位
        max-wait: 1000ms
